apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "managed-tenants.redhat.com.starburst-addon-operator/v1alpha1",
          "kind": "StarburstAddon",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "starburst-addon-operator",
              "app.kubernetes.io/instance": "starburstaddon-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "starburstaddon",
              "app.kubernetes.io/part-of": "starburst-addon-operator"
            },
            "name": "starburstaddon-sample"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-04-25T13:53:35Z"
    operators.operatorframework.io/builder: operator-sdk-v1.28.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: starburst-addon-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: StarburstAddon is the Schema for the starburstaddons API
      displayName: Starburst Addon
      kind: StarburstAddon
      name: starburstaddons.managed-tenants.redhat.com.starburst-addon-operator
      version: v1alpha1
    required:
    - kind: StarburstEnterprise
      name: starburstenterprises.charts.starburstdata.com
      version: v1alpha1
  description: Starburst Addon
  displayName: Starburst Addon
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - managed-tenants.redhat.com.starburst-addon-operator
          resources:
          - starburstaddons
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - managed-tenants.redhat.com.starburst-addon-operator
          resources:
          - starburstaddons/finalizers
          verbs:
          - update
        - apiGroups:
          - managed-tenants.redhat.com.starburst-addon-operator
          resources:
          - starburstaddons/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - alertmanagers
          - alertmanagers/finalizers
          - alertmanagerconfigs
          - prometheuses
          - prometheuses/finalizers
          - thanosrulers
          - thanosrulers/finalizers
          - servicemonitors
          - podmonitors
          - probes
          - prometheusrules
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - charts.starburstdata.com
          resources:
          - starburstenterprises
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - charts.starburstdata.com
          resources:
          - starburstenterprises/finalizers
          verbs:
          - update
        - apiGroups:
          - charts.starburstdata.com
          resources:
          - starburstenterprises/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: starburst-addon-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: starburst-addon-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: starburst-addon-operator
          control-plane: controller-manager
        name: starburst-addon-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - command:
                - /addon
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                image: quay.io/tmihalac/starburst-addon-operator:v0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: starburst-addon-operator-controller-manager
              terminationGracePeriodSeconds: 10
      - label:
          app.kubernetes.io/component: validation-webhook
          app.kubernetes.io/created-by: starburst-addon-operator
          app.kubernetes.io/instance: validation-webhook-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: starburst-addon-operator
          control-plane: validation-webhook-manager
        name: starburst-addon-operator-validate-enterprise-webhook
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: validation-webhook-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: validation-webhook-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - command:
                - /webhook
                - --tls-cert=/tmp/k8s-webhook-server/serving-certs/tls.crt
                - --tls-key=/tmp/k8s-webhook-server/serving-certs/tls.key
                - --port=9443
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                image: quay.io/tmihalac/starburst-addon-operator:v0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: starburst-addon-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: starburst-addon-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - key
  - word
  - s
  links:
  - name: Starburst Addon
    url: https://starburst-addon.domain
  maturity: alpha
  provider:
    name: Me
  version: 0.0.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 9443
    deploymentName: starburst-addon-operator-validate-enterprise-webhook
    failurePolicy: Fail
    generateName: validate-enterprise-webhook.managed-tenants.redhat.com.starburst-addon-operator
    rules:
    - apiGroups:
      - charts.starburstdata.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      - DELETE
      resources:
      - starburstenterprises
      scope: '*'
    sideEffects: None
    targetPort: 9443
    timeoutSeconds: 10
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-enterprise
