# This kustomization.yaml is not intended to be run by itself,
# It should be run by config/default
resources:
- webhook.yaml

configurations:
- kustomizeconfig.yaml

replacements:
- path: kustomizereplace.yaml
