apiVersion: example.com.example.com/v1alpha1
kind: ISVAddon
metadata:
  labels:
    app.kubernetes.io/name: isvaddon
    app.kubernetes.io/instance: isvaddon-sample
    app.kubernetes.io/part-of: isv-addon
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: isv-addon
  name: isvaddon-sample
