# This kustomization.yaml is not intended to be run by itself,
# It should be run by config/default
resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# kube-rbac-proxy
- auth_proxy_service.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_client_clusterrole.yaml
# enterprise resources
- enterprise_role.yaml
- enterprise_role_binding.yaml
