apiVersion: starburst.isv.managed/v1alpha1
kind: StarburstAddon
metadata:
  labels:
    app.kubernetes.io/name: starburstaddon
    app.kubernetes.io/instance: starburstaddon-sample
    app.kubernetes.io/part-of: isv-starburst-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: isv-starburst-operator
  name: starburstaddon-sample
