apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: isv-addon
    app.kubernetes.io/instance: webhook-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: isv-addon
    control-plane: validation-webhook-manager
  name: isv-addon-validate-enterprise-webhook-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: validation-webhook-manager
status:
  loadBalancer: {}
